### ISSUE TITLE
Save permission to refresh page

### ISSUE THREAD

**Issue by ymoreiratiti** [leonardovilarinho/vue-acl#40]
On version 3 we have a flag "save".

It's possible to add this flag to version 4?

**Comment by leonardovilarinho** [comment]
No, it was removed from version 4 for security reasons. Because the permission was recorded in SessionStorage, soon anyone could see it.

I recommend that whenever there is a reload make a request for api to validate the login, or else write the user token or some data of it in indexeddb and do the verification in the mounted method of the root component to log in the user.
