### ISSUE TITLE
Maybe a small bug when updating component

### ISSUE THREAD

**Issue by jdriesen** [leonardovilarinho/vue-acl#7]
Hi Leonardo,

I managed to make it work...
And in fact, it's not that difficult at all...

But I think I found a small bug...
Please take a look at this site...
[Sample Site for ACL testing](http://test05.ireporter.be)

**The possible bug...**
It seems that the 'component' where the buttons are defined, is not updating it's own permission...
(it remains 'notloggedin'...)

**See "The ACL Permission" string in the header... it never changes**

[The sourcecode can be found here...](https://github.com/jdriesen/VueJS-2-ACL-Test)

I really hope you can help me out...

Thanks,

Kind regards,
Johnny

PS.: Feel free to use this sources as an extra demo for your project !!
I REALLY LIKE your solution !!

**Comment by leonardovilarinho** [comment]
I'll be working on it, for the time being a prior solution would be to use `this.$ForceUpdate()` to reload the component.

PS: even then the computed property will not be reactive.

**Comment by jdriesen** [comment]
Hi Leonardo,

Thanks for your reply.

A few small remarks
I added this.forceUpdate() and everything is working fine...
BUT ... computed properties are NOT re-executed !!! 
(buttons DO change in the header, though the computed property is still giving me the wrong information (notloggedin)

[See this demo](http://test05.ireporter.be)

I'm looking forward to your solution.

Have a perfect day,
Johnny

**Comment by leonardovilarinho** [comment]
I understand, in this case you really should use the `data`, because the computed properties are updated only when their data is reactive, and in case the `$access` method is not reactive.

Since the data properties are always updated, as the intention is to work in parallel with the vue router is impossible to do something more reactive.

I ran a test without `$forceUpdate()` and it's functional, so you can remove it from the code as long as you use the data property.
