### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by ErickZH** [leonardovilarinho/vue-acl#81]
**Vue js**: 2.6.10
**Vue ACL**: 4.0.7
**Vue Router**: 3.1.3

![Captura de Pantalla 2019-12-19 a la(s) 14 09 55](https://user-images.githubusercontent.com/14044588/71206113-72bb2800-2269-11ea-98a9-c2fa361fa727.png)

With this error my application does not render.

**Comment by regisbaldo** [comment]
Estou tendo o mesmo problema :/

**Comment by ErickZH** [comment]
any solutions? @leonardovilarinho

**Comment by ErickZH** [comment]
@regisbaldo Hi, Change version `vue-acl` to `4.1.5`

**Comment by thomasleveil** [comment]
I've got the same error despite using vue-acl@4.1.7 😞

**Comment by ErickZH** [comment]
I no longer have a problem loading my app, but I realized that Roles do not work. A user with role x can access the user's resource with role y.

It would be best to start looking for alternatives to this package :(

**Comment by leonardovilarinho** [comment]
Hello everyone,

only with the error message is it very rare for me to be able to replicate it for testing and correction. Please enter the steps for reproducing the error.

I had this error only once, it happened because I created an infinite loop with the permission settings that I registered. So it's worth reviewing all defined rules.

Another thing I want to point out again is that the package is open source and has a code that is easy to understand, any of you could study the error and fix it before waiting for a savior. If you still prefer to look for another package, feel free.

Finally, there are no permission errors as mentioned in the last comment, I use this package in several professional projects and I never had any problems like that. Probably the permission definitions that you created are wrong, if you want to upload an example of how you are using the permissions we can take a look and guide you.

I uploaded the repository with an updated demo if needed. If there are errors, please do not forget the steps for reproducing it.

PS: sorry for my english
