### ISSUE TITLE
How to assign multple permissions to user?

### ISSUE THREAD

**Issue by SapneshNaik** [leonardovilarinho/vue-acl#83]

**Comment by yichinweng** [comment]
same question, how does the 'isLogged' rule work if user just can be 'user' or 'inside' ?

**Comment by lon9man** [comment]
+1

**Comment by robov** [comment]
+1 I would rather verify against a set of permissions than against a specific role

**Comment by SapneshNaik** [comment]
@robov I have done exactly what you've described here. Though I implemented my own logic and didn't use this plugin. See https://github.com/SapneshNaik/Student-Management-System

**Comment by rupas385** [comment]
same question here, @leonardovilarinho, is very useful if you add method like acl.add('permission') instead on change... and also have methods for clear current permission, but only change permission limit this library. 

Regards

**Comment by leonardovilarinho** [comment]
Hello, sorry for the delay.

The plugin already supports multi-permissions, but I think some got lost when trying to understand the method as the plugin handles the rules.

It consists of rules, but each rule has a whitelist, which you create using AND or OR. Let's take an example of a blog:

- isWriter: comment AND write AND torevision
- isReviser: comment AND write AND publish
- isAdmin: comment AND write AND torevision AND publish

We have a rule for each type of user and each user has certain permissions. For example, when a writer logs into the system, I must run `this.$acl.change(['comment', 'write', 'torevision'])` so that he can access the routes that demand these permissions and we can identify him from a global form by the `isWriter` rule.

We can't get away from it too much because the ACL plugin must be the only true source of the access rules, if we allow the application to edit the rules at run time we would be breaking the flow of truth, which should never be done.

I understand that some systems can allow an admin to add a custom permission for each user, in these cases just use the OR clause of the rule.

Sorry for my bad English, it's the best I can at the moment haha

PS: I will try to pay more attention to the repositories, I spent some time with some problems that made it impossible for me.

**Comment by leonardovilarinho** [comment]
In the case of the tip to have the `add` method I will think about implementing it, as this may affect the question of the source of truth I mentioned a little. However, a current way of doing this may be:

```javascript
this.$acl.change(this.$acl.get.concat(['read', 'write']))
```

**Comment by desmartDev** [comment]
Hey, it works nice. So, please add this on README.md

**Comment by leonardovilarinho** [comment]
All right, I'll add it to readme.md
